### ISSUE TITLE
Figure out how to distribute with Yarn 2

### ISSUE THREAD

**Issue by cjdenio** [Standard-Structure/struct#33]
Because Yarn 2 doesn't have `node_modules`, it's not compatible with npm. As such, is it even possible to distribute `struct` on npm? (as both a library and a CLI)

@eankeen might know more about this.

**Comment by eankeen** [comment]
hai, sorry i didn't respond sooner - was offline

the fact that `node_modules` folder does or doesn't exist isn't relevant with respect to publishability / distribuitability. we can use any package manager's publishing command to distribute our package if one doesn't already exist within yarn 2. this is because library dependency resolution is basically determined from the `package.json` file, not from reading the fs (`/.node_modules`). i've personally used `npm publish`, `yarn publish`, `pnpm publish` all interchangeably and they are roughly similar. one thing to keep in mind is if we use the workspace protocol (meaning packages are defined as like `"fox-utils": "workspace:^1.1.4",`), we'll definitely need to use `pnpm publish` or `yarn publish`, since they strip the `workspace` before publishing (so it can be consumed by regular users)

**Comment by eankeen** [comment]
i'll also add that i've personally never published any packages that have had dependencies managed by berry, but this flow doesn't seem to be all that different or special compared with conventional package managers

**Comment by cjdenio** [comment]
I'm having issues running the CLI locally, though, because Node can't find any `node_modules`.

I really don't want to type `yarn node bin/cli.js generate` every time :weary:

**Comment by eankeen** [comment]
oh i see, yeah that's not a distribution issue. what's the command you want to run?
